### ISSUE TITLE
powerboard

### ISSUE THREAD

**Issue by Darthpbal** [Darthpbal/eclipse-ASUPayload#24]
- [x] design and document subcircuit. Add to master.
  - [ ] using relevant subcircuit, demo sensor alone, verify accuracy
  - [ ] Demo operating next to other sensors while logging to sd card compatible with desired logging speed, reverify accuracy.
  - [ ] Implement code into the master program on a unique git branch, retest and reverify, then merge into the master project branch.

**Comment by Darthpbal** [comment]
powerboost500 guide [page](https://learn.adafruit.com/adafruit-powerboost-500-shield-rechargeable-battery-pack)

**Comment by Darthpbal** [comment]
set up test:
set up arduino to log UTC timestamp and millis timestamp from GPS and clock along with current voltage to an sd card such that it can be left alone to record while the battery dies.

**Comment by Darthpbal** [comment]
measured voltage is unexpectedly low. 

#todo
 - [ ] double check battery voltage using multimeter
 - [ ] check battery voltage when 4400mAH batt is plugged in. 
 - [ ] Run system on a higher current consuming load to see what happens when the system dies. How an SD card behaves during this event would be interesting to see.
